name: Resize images

on:
  pull_request:
  push:
    paths:
      - "linuxserver.io/img/**"
    branches-ignore:
      - "master"

jobs:
  summary-syncer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          fetch-depth: "0"
          ref: ${{ github.head_ref }}

      - name: Resize images
        run: |
          docker run -d --rm --name imagemagick -v "$(pwd)/linuxserver.io":/inn -e FOLDER='/inn/img/' -e WIDTH=192 -e HEIGHT=192 ghcr.io/linuxserver/baseimage-alpine:3.24
          docker exec imagemagick bash -c 'apk add --no-cache imagemagick && for f in "${FOLDER%/}"/*-logo.png "${FOLDER%/}"/*-icon.png; do if [[ $(identify -format "%w" "${f}") -gt "${WIDTH}" ]] || [[ $(identify -format "%h" "${f}") -gt "${HEIGHT}" ]]; then magick mogrify -resize "${WIDTH}x${HEIGHT}>" "${f}"; fi; done'
          docker stop imagemagick

          git config --global user.email "ci@linuxserver.io"
          git config --global user.name "LinuxServer-CI"
          git commit -am "Automated Resizing of images" || :
          git push || :
